### ISSUE TITLE
R6 methods don't allow double-indented formals?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#1136]
The following should be allowed (ref: https://style.tidyverse.org/functions.html#long-lines-1 doesn't mention R6):

```r
R6Class("MyClass",
  public = list(
    param = NULL,
    initialize = function(
      my_long_parameter = getOption("default_long_parameter", 1)) {
      self$param <- my_long_parameter
    }
  )
)
```

But it's currently re-styled (`style_text()` output):

```r
R6Class("MyClass",
  public = list(
    param = NULL,
    initialize = function(my_long_parameter = getOption("default_long_parameter", 1)) {
      self$param <- my_long_parameter
    }
  )
)
```

Which of course creates an over-full line.

**Comment by lorenzwalthert** [comment]
Right… but I think in your example, you only put one level of indention. Shouldn’t it be 
```r
R6Class("MyClass",
  public = list(
    param = NULL,
    initialize = function(
        my_long_parameter = getOption("default_long_parameter", 1)) {
      self$param <- my_long_parameter
    }
  )
)
```

**Comment by MichaelChirico** [comment]
ah yes, my mistake. edited in the description

**Comment by lorenzwalthert** [comment]
Seems like detection of double indention is based on the absolute indention of the formals, instead of the relative...

**Comment by lorenzwalthert** [comment]
This is actually fixed with #1235 I belive, as double indention is not allowed anymore. Can you double check @MichaelChirico?

**Comment by MichaelChirico** [comment]
Unfortunately no, the same bug still applies to the new style guide approach:

```r
styler::style_text(R"(
R6Class("MyClass",
  public = list(
    param = NULL,
    initialize = function(
      my_long_parameter = getOption("default_long_parameter", 1)
    ) {
      self$param <- my_long_parameter
    }
  )
)
)")
```

gives output

```r
R6Class("MyClass",
  public = list(
    param = NULL,
    initialize = function(my_long_parameter = getOption("default_long_parameter", 1)) {
      self$param <- my_long_parameter
    }
  )
)
```

**Comment by MichaelChirico** [comment]
(updated the bug title since it's not about double-indentation _per se_, but about declaring R6 methods with multi-line formals, under either old or new guide style)

**Comment by lorenzwalthert** [comment]
Seems not a problem in unnested case:
``` r
styler::style_text('initialize <- function(
    my_long_parameter = getOption("default_long_parameter", 1)) {
  self$param <- my_long_parameter
}')
#> Warning: Could not use `colored = TRUE`, as the package prettycode is not installed.
#> Please install it if you want to see colored output or see
#> `?styler::print.vertical()` for more information.
#> initialize <- function(
#>     my_long_parameter = getOption("default_long_parameter", 1)) {
#>   self$param <- my_long_parameter
#> }
```

<sup>Created on 2024-12-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by lorenzwalthert** [comment]
I am open to PRs 😊
